(defun erlcscope-reload-all (rdir)
  (interactive "DSpecify the top directory: ")
  (setq dir (file-truename rdir))
  (setq cscope_files_path (expand-file-name "cscope.files" dir))
  (cond ((file-exists-p cscope_files_path)
    (delete-file cscope_files_path)))
  (message (concat "generate index.. " dir))
  (call-process "erlcscope" nil "*erlcscope*" nil dir)
  (message "erlcscope: generate ok")
  (ascope-init (concat dir "/"))
)

(global-set-key (kbd "C-c s R") 'erlcscope-reload-all)
