(defun erlcscope-reload-all ()
  (interactive)
  (setq pwd (getenv "PWD"))
  (setq cscope_files_path (expand-file-name "/cscope.files" pwd))
  (cond ((file-exists-p cscope_files_path)
    (delete-file cscope_files_path)))
  (message (concat "generate index.. " pwd))
  (call-process "erlcscope" nil "*erlcscope*" nil pwd)
  (message "erlcscope: generate ok")
  (ascope-init (concat pwd "/"))
)

(global-set-key (kbd "C-c s R") 'erlcscope-reload-all)
